"""Stub for winreg — Windows registry access.

Minimal stubs covering the surface area used in pysysfan.
"""

from typing import Any

HKEY_LOCAL_MACHINE: int
HKEY_CURRENT_USER: int

class WindowsError(OSError): ...

def OpenKey(key: int, sub_key: str, reserved: int = 0, access: int = 0) -> int: ...
def QueryInfoKey(key: int) -> tuple[int, int, int]: ...
def EnumKey(key: int, index: int) -> str: ...
def QueryValueEx(key: int, name: str) -> tuple[Any, int]: ...
def CloseKey(key: int) -> None: ...
