"""Linux hardware implementation using lm-sensors (pysensors) and sysfs.

This module provides Linux-specific hardware access via:
- pysensors library for sensor enumeration
- sysfs hwmon interface for sensor reading
- Direct sysfs PWM control for fan management
- ThinkPad-specific support via /proc/acpi/ibm/fan
"""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from pysysfan.platforms.base import (
    BaseHardwareManager,
    ControlInfo,
    HardwareScanResult,
    SensorInfo,
    SensorKind,
)

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)

# sysfs paths
SYSFS_HWMON = Path("/sys/class/hwmon")
SYSFS_THERMAL = Path("/sys/class/thermal")
THINKPAD_FAN_PATH = Path("/proc/acpi/ibm/fan")


class LinuxHardwareManager(BaseHardwareManager):
    """Linux hardware manager using lm-sensors and sysfs.

    Supports:
    - Generic hwmon sensors (temperatures, fans, voltages)
    - PWM fan control via sysfs
    - ThinkPad-specific fan control via thinkpad_acpi

    Usage:
        with LinuxHardwareManager() as hw:
            result = hw.scan()
            for temp in result.temperatures:
                print(f"{temp.sensor_name}: {temp.value}°C")
    """

    def __init__(self):
        super().__init__()  # Initialize base class (sets up _off_mode_fans)
        self._sensors = None
        self._chips: dict[str, dict] = {}  # chip_name -> chip_info
        self._controls: dict[str, dict] = {}  # identifier -> control_info
        self._is_thinkpad = False

    def open(self) -> None:
        """Initialize sensors library and detect hardware capabilities."""
        try:
            import sensors

            sensors.init()
            self._sensors = sensors
            logger.info("LinuxHardwareManager: sensors library initialized")
        except ImportError as e:
            logger.error(
                "pysensors library not installed. Install with: pip install pysensors"
            )
            raise RuntimeError(
                "pysensors library required. Install with: pip install pysensors"
            ) from e
        except Exception as e:
            logger.error(f"Failed to initialize sensors library: {e}")
            raise RuntimeError(f"Failed to initialize sensors: {e}") from e

        # Detect ThinkPad
        self._is_thinkpad = self._detect_thinkpad()
        if self._is_thinkpad:
            self._ensure_thinkpad_fan_control()

        # Discover available hardware
        self._discover_hardware()

        logger.info("LinuxHardwareManager opened successfully")

    def close(self) -> None:
        """Cleanup and restore default fan control."""
        if self._sensors is not None:
            self.restore_defaults()
            try:
                self._sensors.cleanup()
            except Exception as e:
                logger.warning(f"Error cleaning up sensors: {e}")
            self._sensors = None
            self._chips.clear()
            self._controls.clear()
            logger.info("LinuxHardwareManager closed")

    def _detect_thinkpad(self) -> bool:
        """Detect if this is a ThinkPad laptop."""
        try:
            dmi_path = Path("/sys/class/dmi/id/product_name")
            if dmi_path.exists():
                product_name = dmi_path.read_text().strip()
                is_thinkpad = "thinkpad" in product_name.lower()
                if is_thinkpad:
                    logger.info(f"Detected ThinkPad: {product_name}")
                return is_thinkpad
        except Exception as e:
            logger.debug(f"Could not detect ThinkPad: {e}")
        return False

    def _ensure_thinkpad_fan_control(self) -> None:
        """Ensure thinkpad_acpi has fan_control enabled.

        Auto-creates modprobe config if needed and reloads module.
        """
        if not THINKPAD_FAN_PATH.exists():
            logger.warning("ThinkPad detected but /proc/acpi/ibm/fan not found")
            return

        try:
            # Check if fan control is available
            content = THINKPAD_FAN_PATH.read_text()
            if "level:" in content:
                logger.info("ThinkPad fan control already enabled")
                return

            # Need to enable fan_control
            self._enable_thinkpad_fan_control()

        except PermissionError:
            logger.warning(
                "Cannot access ThinkPad fan control (permission denied). "
                "Run as root or enable fan_control manually."
            )
        except Exception as e:
            logger.error(f"Error checking ThinkPad fan control: {e}")

    def _enable_thinkpad_fan_control(self) -> None:
        """Enable fan_control parameter for thinkpad_acpi."""
        modprobe_path = Path("/etc/modprobe.d/thinkpad-pysysfan.conf")

        try:
            # Create modprobe config
            modprobe_content = (
                "# Auto-generated by pysysfan\noptions thinkpad_acpi fan_control=1\n"
            )
            modprobe_path.write_text(modprobe_content)
            logger.info(f"Created {modprobe_path} to enable ThinkPad fan control")

            # Reload module (requires root)
            subprocess.run(
                ["modprobe", "-r", "thinkpad_acpi"],
                capture_output=True,
                text=True,
            )
            result = subprocess.run(
                ["modprobe", "thinkpad_acpi", "fan_control=1"],
                capture_output=True,
                text=True,
            )

            if result.returncode == 0:
                logger.info("ThinkPad fan control enabled successfully")
            else:
                logger.warning(
                    f"Could not reload thinkpad_acpi module: {result.stderr}"
                )

        except PermissionError:
            logger.warning(
                "Cannot enable ThinkPad fan control (permission denied). "
                "Run as root or manually create /etc/modprobe.d/thinkpad-pysysfan.conf"
            )
        except Exception as e:
            logger.error(f"Error enabling ThinkPad fan control: {e}")

    def _discover_hardware(self) -> None:
        """Discover available hardware sensors and controls."""
        self._chips.clear()
        self._controls.clear()

        # Iterate through pysensors chips
        try:
            for chip in self._sensors.iter_detected_chips():
                chip_name = str(chip)
                self._chips[chip_name] = {
                    "chip": chip,
                    "hwmon_path": self._find_hwmon_path(chip_name),
                }

                # Check for PWM controls in sysfs
                hwmon_path = self._chips[chip_name]["hwmon_path"]
                if hwmon_path and hwmon_path.exists():
                    self._discover_pwm_controls(hwmon_path, chip_name)

        except Exception as e:
            logger.error(f"Error discovering hardware: {e}")

        # Add ThinkPad control if available
        if THINKPAD_FAN_PATH.exists() and self._is_thinkpad:
            self._controls["thinkpad/fan"] = {
                "type": "thinkpad",
                "path": THINKPAD_FAN_PATH,
                "hwmon_path": None,
            }

        logger.info(
            f"Discovered {len(self._chips)} chips, {len(self._controls)} controllable outputs"
        )

    def _find_hwmon_path(self, chip_name: str) -> Path | None:
        """Find the sysfs hwmon path for a given chip."""
        try:
            for hwmon_dir in SYSFS_HWMON.glob("hwmon*"):
                name_file = hwmon_dir / "name"
                if name_file.exists():
                    name = name_file.read_text().strip()
                    # Match chip name (e.g., "coretemp" matches "coretemp-isa-0000")
                    if name in chip_name or chip_name.startswith(name):
                        return hwmon_dir
        except Exception as e:
            logger.debug(f"Error finding hwmon path for {chip_name}: {e}")
        return None

    def _discover_pwm_controls(self, hwmon_path: Path, chip_name: str) -> None:
        """Discover PWM fan controls in hwmon directory."""
        try:
            for pwm_file in hwmon_path.glob("pwm*"):
                if pwm_file.is_file() and pwm_file.name.startswith("pwm"):
                    pwm_num = pwm_file.name.replace("pwm", "")
                    if pwm_num.isdigit():
                        identifier = f"{hwmon_path.name}/pwm{pwm_num}"
                        self._controls[identifier] = {
                            "type": "pwm",
                            "path": pwm_file,
                            "enable_path": hwmon_path / f"pwm{pwm_num}_enable",
                            "chip_name": chip_name,
                            "hwmon_path": hwmon_path,
                        }
                        logger.debug(f"Found PWM control: {identifier}")
        except Exception as e:
            logger.debug(f"Error discovering PWM controls: {e}")

    def _get_chip_features(self, chip):
        """Iterate over all features in a chip."""
        try:
            for feature in chip:
                yield feature
        except Exception as e:
            logger.debug(f"Error iterating chip features: {e}")

    def _get_subfeatures(self, feature):
        """Iterate over all subfeatures in a feature."""
        try:
            for subfeature in feature:
                yield subfeature
        except Exception as e:
            logger.debug(f"Error iterating subfeatures: {e}")

    def scan(self) -> HardwareScanResult:
        """Perform a full hardware scan."""
        result = HardwareScanResult()

        # Scan pysensors chips
        for chip_name, chip_info in self._chips.items():
            chip = chip_info["chip"]

            try:
                for feature in self._get_chip_features(chip):
                    for subfeature in self._get_subfeatures(feature):
                        try:
                            subfeature_name = (
                                subfeature.name
                                if hasattr(subfeature, "name")
                                else str(subfeature)
                            )
                            value = subfeature.get_value()

                            # Determine sensor type from subfeature name
                            sensor_type, sensor_kind = self._classify_sensor(
                                subfeature_name
                            )

                            identifier = f"{chip_name}/{subfeature_name}"

                            info = SensorInfo(
                                hardware_name=chip_name.split("-")[
                                    0
                                ],  # e.g., "coretemp" from "coretemp-isa-0000"
                                hardware_type="Generic",
                                sensor_name=subfeature_name,
                                sensor_type=sensor_type,
                                identifier=identifier,
                                value=value if value != 0.0 else None,
                            )
                            result.all_sensors.append(info)

                            if sensor_kind == SensorKind.TEMPERATURE:
                                result.temperatures.append(info)
                            elif sensor_kind == SensorKind.FAN:
                                result.fans.append(info)

                        except Exception as e:
                            logger.debug(f"Error reading subfeature {subfeature}: {e}")

            except Exception as e:
                logger.debug(f"Error scanning chip {chip_name}: {e}")

        # Add controls
        for identifier, control_info in self._controls.items():
            current_value = None

            if control_info["type"] == "pwm":
                try:
                    pwm_value = int(control_info["path"].read_text().strip())
                    current_value = (pwm_value / 255.0) * 100.0
                except Exception:
                    pass

                # Check if we have control (pwm_enable is set to 1)
                has_control = False
                try:
                    enable_val = int(control_info["enable_path"].read_text().strip())
                    has_control = enable_val == 1
                except Exception:
                    # Assume we have control if pwm file is writable
                    has_control = os.access(control_info["path"], os.W_OK)

            elif control_info["type"] == "thinkpad":
                current_value = 0.0  # Can't read current level, but we can control
                has_control = os.access(control_info["path"], os.W_OK)

            ctrl_info = ControlInfo(
                hardware_name=control_info.get("chip_name", "System"),
                sensor_name=identifier.split("/")[-1],
                identifier=identifier,
                current_value=current_value,
                has_control=has_control,
            )
            result.controls.append(ctrl_info)

        return result

    def _classify_sensor(self, name: str) -> tuple[str, SensorKind]:
        """Classify sensor type from its name.

        Returns:
            Tuple of (type_name, SensorKind)
        """
        name_lower = name.lower()

        if "temp" in name_lower:
            return ("Temperature", SensorKind.TEMPERATURE)
        elif "fan" in name_lower:
            return ("Fan", SensorKind.FAN)
        elif "in" in name_lower and any(c.isdigit() for c in name):
            return ("Voltage", SensorKind.VOLTAGE)
        elif "power" in name_lower:
            return ("Power", SensorKind.POWER)
        elif "freq" in name_lower or "clock" in name_lower:
            return ("Clock", SensorKind.CLOCK)
        else:
            return ("Unknown", SensorKind.DATA)

    def get_temperatures(self) -> list[SensorInfo]:
        """Get all current temperature readings."""
        result = self.scan()
        return result.temperatures

    def get_fan_speeds(self) -> list[SensorInfo]:
        """Get all current fan speed readings (RPM)."""
        result = self.scan()
        return result.fans

    def set_fan_speed(
        self, control_identifier: str, percent: float, force_zero: bool = True
    ) -> None:
        """Set a fan speed by its control identifier.

        Args:
            control_identifier: The identifier for the control (e.g., "hwmon0/pwm1" or "thinkpad/fan")
            percent: Speed percentage (0-100). Values are clamped.
            force_zero: If True, actively set 0% duty cycle. If False, release to automatic.
        """
        if control_identifier not in self._controls:
            raise ValueError(
                f"Control '{control_identifier}' not found. "
                f"Available controls: {list(self._controls.keys())}"
            )

        percent = max(0.0, min(100.0, percent))
        control_info = self._controls[control_identifier]

        if control_info["type"] == "pwm":
            self._set_pwm_speed(control_info, percent)
        elif control_info["type"] == "thinkpad":
            self._set_thinkpad_speed(percent)
        else:
            raise ValueError(f"Unknown control type: {control_info['type']}")

    def _set_pwm_speed(self, control_info: dict, percent: float) -> None:
        """Set PWM fan speed."""
        pwm_value = round((percent / 100.0) * 255)
        pwm_path = control_info["path"]
        enable_path = control_info["enable_path"]

        try:
            # First, enable manual control if needed
            if enable_path.exists():
                current_mode = int(enable_path.read_text().strip())
                if current_mode != 1:
                    enable_path.write_text("1")
                    logger.debug(f"Enabled manual control for {pwm_path}")

            # Set the PWM value
            pwm_path.write_text(str(pwm_value))
            logger.debug(f"Set PWM {pwm_path} to {pwm_value} ({percent:.1f}%)")

        except PermissionError as e:
            raise PermissionError(
                "Cannot set fan speed: permission denied. Run as root."
            ) from e
        except Exception as e:
            raise RuntimeError(f"Failed to set fan speed: {e}") from e

    def _set_thinkpad_speed(self, percent: float) -> None:
        """Set ThinkPad fan speed.

        ThinkPad uses levels 0-7, plus 'auto' and 'disengaged'.
        Map percentage to appropriate level.
        """
        # Map percentage to ThinkPad levels
        if percent == 0:
            level = 0  # Off (if supported)
        elif percent <= 14:
            level = 1
        elif percent <= 28:
            level = 2
        elif percent <= 42:
            level = 3
        elif percent <= 56:
            level = 4
        elif percent <= 70:
            level = 5
        elif percent <= 84:
            level = 6
        else:
            level = 7  # Full speed

        try:
            THINKPAD_FAN_PATH.write_text(f"level {level}")
            logger.debug(f"Set ThinkPad fan to level {level} ({percent:.1f}%)")
        except PermissionError as e:
            raise PermissionError(
                "Cannot set ThinkPad fan speed: permission denied. Run as root."
            ) from e
        except Exception as e:
            raise RuntimeError(f"Failed to set ThinkPad fan speed: {e}") from e

    def restore_defaults(self) -> None:
        """Restore all fan controls to BIOS/default mode."""
        for identifier, control_info in self._controls.items():
            try:
                if control_info["type"] == "pwm":
                    self._restore_pwm_default(control_info)
                elif control_info["type"] == "thinkpad":
                    self._restore_thinkpad_default()
            except Exception as e:
                logger.warning(f"Failed to restore default for {identifier}: {e}")

    def _restore_pwm_default(self, control_info: dict) -> None:
        """Restore PWM control to BIOS mode."""
        enable_path = control_info["enable_path"]
        if enable_path.exists():
            try:
                enable_path.write_text("0")  # 0 = BIOS control
                logger.debug(f"Restored BIOS control for {control_info['path']}")
            except PermissionError:
                logger.warning(f"Permission denied restoring {enable_path}")
            except Exception as e:
                logger.warning(f"Error restoring {enable_path}: {e}")

    def _restore_thinkpad_default(self) -> None:
        """Restore ThinkPad fan to automatic control."""
        try:
            THINKPAD_FAN_PATH.write_text("level auto")
            logger.debug("Restored ThinkPad fan to automatic control")
        except PermissionError:
            logger.warning("Permission denied restoring ThinkPad fan control")
        except Exception as e:
            logger.warning(f"Error restoring ThinkPad fan: {e}")

    def get_hardware_fingerprint(self) -> str:
        """Get a fingerprint of the current hardware configuration.

        Uses chip names and control identifiers to detect changes.
        """
        import hashlib

        chip_names = sorted(self._chips.keys())
        control_ids = sorted(self._controls.keys())

        fingerprint_parts = chip_names + control_ids
        fingerprint_data = ";".join(fingerprint_parts)

        return hashlib.sha256(fingerprint_data.encode()).hexdigest()
