name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting and lint
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github ."
      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."

  test:
    runs-on: windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: |
          uv run pytest | Tee-Object -FilePath pytest_output.txt
          echo "## Coverage Summary" >> $env:GITHUB_STEP_SUMMARY
          echo '```text' >> $env:GITHUB_STEP_SUMMARY
          Select-String -Path pytest_output.txt -Pattern '^Name.*Stmts','^TOTAL' | ForEach-Object { $_.Line } >> $env:GITHUB_STEP_SUMMARY
          echo '```' >> $env:GITHUB_STEP_SUMMARY
        shell: pwsh
